// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

function customAdd(a, b) {
  return a + b;
}

var Sample = {
  customAdd: customAdd
};

function dispatch(call, chain) {
  if (call[0] !== "add") {
    return Curry._1(chain, call);
  }
  var match = call[1];
  if (match.length !== 2) {
    return Curry._1(chain, call);
  }
  var a = match[0];
  if (typeof a === "number") {
    return Curry._1(chain, call);
  }
  if (a.TAG !== /* LvNumber */1) {
    return Curry._1(chain, call);
  }
  var b = match[1];
  if (typeof b === "number" || b.TAG !== /* LvNumber */1) {
    return Curry._1(chain, call);
  } else {
    return {
            TAG: /* Ok */0,
            _0: {
              TAG: /* LvNumber */1,
              _0: a._0 + b._0
            }
          };
  }
}

var LV;

exports.LV = LV;
exports.Sample = Sample;
exports.dispatch = dispatch;
/* No side effect */
