// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function interperse(aList, seperator) {
  if (aList) {
    return {
            hd: aList.hd,
            tl: {
              hd: seperator,
              tl: interperse(aList.tl, seperator)
            }
          };
  } else {
    return /* [] */0;
  }
}

exports.interperse = interperse;
/* No side effect */
