// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_exn = require("rescript/lib/js/js_exn.js");
var Caml_js_exceptions = require("rescript/lib/js/caml_js_exceptions.js");
var ReducerExternal_LispLibrary = require("../ReducerExternal/ReducerExternal_LispLibrary.bs.js");

function callMatjJs(_functionCall) {
  return {
          TAG: /* Error */1,
          _0: "TODO call MathJs"
        };
}

function dispatch(call) {
  try {
    return ReducerExternal_LispLibrary.dispatch(call, callMatjJs);
  }
  catch (raw_obj){
    var obj = Caml_js_exceptions.internalToOCamlException(raw_obj);
    if (obj.RE_EXN_ID === Js_exn.$$Error) {
      var m = obj._1.message;
      if (m !== undefined) {
        return {
                TAG: /* Error */1,
                _0: "RunTime Error " + m
              };
      } else {
        return {
                TAG: /* Error */1,
                _0: "RunTime Error "
              };
      }
    }
    throw obj;
  }
}

var LV;

var Lib;

exports.LV = LV;
exports.Lib = Lib;
exports.callMatjJs = callMatjJs;
exports.dispatch = dispatch;
/* No side effect */
